server:
  port: 8001

spring:
  application:
    name: admin-client

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      user.name: admin         #These two are needed so that the server
      user.password: 123456    #can access the protected client endpoints
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
